# action.yml
name: 'DefectDojo'
description: 'Using DefectDojo CLI'
inputs:
  arguments:  # id of input
    description: 'Arguments to add'
    required: false
outputs:
  response:
    description: 'DefectDojo publish result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
