# action.yml
name: 'DefectDojo'
description: 'Using DefectDojo CLI'
inputs:
  command:  # id of input
    description: 'Command to run'
    required: false
outputs:
  response:
    description: 'DefectDojo publish result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_DEFECTDOJO_URL: ${{ inputs.defectdojo_url }}
    INPUT_DEFECTDOJO_ENDPOINT: ${{ inputs.defectdojo_endpoint }}
  args:
    - ${{ inputs.command }}
