on: [push]
jobs:
  dd:
    runs-on: ubuntu-latest
    name: Simple test of action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test run
        id: dd
        uses: ./ # Uses an action in the root directory
        with:
          arguments: '--help'
