on: [push]

jobs:
  dd:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test run
        id: dd
        uses: ./ # Uses an action in the root directory
        with:
          command: '--help'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Response ${{ steps.dd.outputs.response }}"
